services:
  - type: docker
    name: postgres-sql-bsn
    plan: free
    dockerfilePath: ""
    dockerComposePath: ./docker-compose.yml

  - type: web
    name: spring-app
    env: docker
    plan: free
    buildCommand: ""
    startCommand: ""
    dockerfilePath: ./Dockerfile
    dependsOn:
      - postgres-sql-bsn
